### PR TITLE
Optimize mini ico using leanify

### PR DESCRIPTION
**Pull request by JayXon**

### CODE REVIEW

**Comment by angea** [comment]
Nice! Can you also improve the compression of the other formats embedding PNGs (videos such as quicktime, mp4, mkv...)?

**Comment by JayXon** [comment]
leanify currently does not support any video formats, so I'm not very familiar with them, I probably can make it support mp4, the format looks simple, but I need to learn more about it, I had no idea you can use png as a frame in mp4!

I'm also planning to send PR for gzip (better compression) and swf (if you accept deflate or lzma compressed swf).

**Comment by angea** [comment]
True for SWF but in this case I'd keep them as CWS and ZWF separate files

**Comment by angea** [comment]
btw FLV is not SWF, so forget what I said.

**Comment by angea** [comment]
leanified the other files. Thanks!

**Pull request closed without merging**
